### PR TITLE
override specialization for std::copy

### PR DESCRIPTION
**Pull request by user706**
Theres a new header an cpp now, for overriding `std::copy`

```
xxxxxxxxxxxxxxxx_________________xxxxxxx
                |                |
                l_               f_

Copying takes place in 2 parts: 

- from f_ to &a_[N]
- from a_ to l_
```

Run the binary after an optimized build... once with 
this comment in place https://github.com/user706/ca/blob/04c95868554fa26c999859571e46edd8b91a5bb5/array.cpp#L3
(will then use the override - fast)
and once with the comment removed (slow)

### CODE REVIEW

**Comment by user706** [comment]
Ah I left this stuff here
https://github.com/user1095108/ca/compare/user1095108:master...user706:overrides?expand=1#diff-b37cceb5282c01145f3dd62773f61917c86cb4dcfd20bba31c2d65f66941a871R208
in by mistake.

It's not needed (or maybe it can be made private and used internally...).

**Comment by user706** [comment]
Ah I left this stuff here
https://github.com/user1095108/ca/compare/user1095108:master...user706:overrides?expand=1#diff-b37cceb5282c01145f3dd62773f61917c86cb4dcfd20bba31c2d65f66941a871R208
in by mistake.

It's not needed (or maybe it can be made private and used internally...).

**Comment by user1095108** [comment]
I see no reason why your split `std::copy()` would do any better than a plain `std::copy()`. ca::array is now a random-access container and should work better with `std::copy()` than before, especially with `std::execution::unseq`. If your modifications were less involved: you have a plethora of begins() and ends(), I'd give you a `contrib.hpp` header file for your contributions. But I don't think you've tested these ideas. So this is more something for your fork or your private utility header file.

Anyway, I'd do this, first() and last() accessors for you, not the various begins and ends and your very own contrib.hpp for your contributions.

What could maybe be worthwhile is a split `memcpy()`, since a direct `memcpy()` is not possible, but `std::copy()` should work as expected, unsplit.

I have changed array.cpp and array.hpp to that effect:
`std::copy(ca.cbegin(), ca.cend(), std::ostream_iterator<int>(std::cout, "\n"));`

constexpr auto data() const noexcept { return a_; }
constexpr auto first() const noexcept { return f_; }
constexpr auto last() const noexcept { return l_; }
static constexpr size_type array_size() noexcept { return N; } // CAP + 1

So, your own contrib.hpp and contrib.cpp for the tests, if you like? I'm using this class as a request queue in my trading app, so I'd like to keep it simple, easily understandable.

**Comment by user706** [comment]
Sorry about the needless plathora of begin() ends().

They were never used.

The speedup is this: I do not use the iterators, but rip out the underlying plain old pointers and use those.
(So where is then the big speedup? the special iterator++ operations are no longer used)

**Comment by user1095108** [comment]
Is this ok for you?
```
template <typename T, std::size_t S, enum Method M>
inline void split(array<T, S, M> const& a, auto g)
```

**Comment by user706** [comment]
> Is this ok for you?
> 
> ```
> template <typename T, std::size_t S, enum Method M>
> inline void split(array<T, S, M> const& a, auto g)
> ```

Nice idea thanks. Only problem is that this assumes an iteration from `f_` to `l_`, which might not always be the case.
(For example... [this line](https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/array.cpp#L23) could be changed to have `std::next(ca.cbegin())` instead)

So I've put something similar (working with iterators) [here](https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayiterator.hpp#L177), which calls [this](https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayiterator.hpp#L166):

```cpp
template <typename T>
constexpr void iterRawConst(const T *f, const T *l, const T *dataStart, const T *dataEnd, auto&& g)
{
  if (l - f < 0)
  {
    g(f, dataEnd);
    f = dataStart;
  }
  g(f, l);
}
```


You can watch it in action via debug, where you'll see that the outer call, that causes entry into it, is [here](https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/array.cpp#L23).

That's kindof working.

Then I've tried to **generically** handle [this stuff](https://github.com/user706/ca/blob/overrides/arrayoverrides.hpp#L56) in a similar manner, but it's damn hard. I'll leave it for now.

What is hard about it:

Handling the copying from one ring to another ring... by fragmenting into.... into (not 2) but at most 3 (or is it 4? (***)) copyable regions

Example - copy from `src` to `dst`:
```
Copy from src     from a to c... 
  into    dst     into l                    ("l" - last)

src:  ccc---------------------aaaaabbbbbbb
dst:  -------------------------------l----

So that I first copy a, then b, then c to get

dst:  bbbbbbbccc---------------------aaaaa
```
Above the 3 copyable regions are `aaaaa`, then `bbbbbbb`, then `ccc`

(***) Probably at most 3 regions, but the logic would be such, that it has 4 potential calls to `g` (with only 3 being entered)

```cpp
if (l - f < 0) {          //e.g. https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayoverrides.hpp#L71
  if (l2 - f2 < 0) {      
    g(...?);              //e.g. https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayoverrides.cpp#L13
  }
  g(...?);                //e.g. https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayoverrides.cpp#L17
}                         //e.g. https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayoverrides.hpp#L78
if (l2 - f2 < 0) {
  g(...?);                //e.g. https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayoverrides.cpp#L13
}
g(...?)                   //e.g. https://github.com/user706/ca/blob/36aa18f830d27240a65fe0ea4216007717fb426a/arrayoverrides.cpp#L17
```

I don't even know if it cleanly works with the g() passed in from the outside completely like that, because some data only comes into existence later via variables.

**Comment by user1095108** [comment]
I'll write a better split after some zzzz, but imo you should be spending time writing apps, not containers. The next big thing (tm).

**Comment by user706** [comment]
Haha, true!

**Comment by user706** [comment]
I'm kindof wandering about your trading app... to be honest.
PS: You might enjoy this indian guru-comedian: https://www.youtube.com/watch?v=DDEMr_sIsDg

**Comment by user1095108** [comment]
It's just decimal float + indicators + graphical display of them. I'm hoping an AI might be able to track, say, 100 indicators and achieve some meaningful results. But it is a herculean effort for very little gain + the AI needs to keep an eye on the news. It's news + news + news + ... which make the price move. The AI can minimize the losses at least :) I think, I wasted a lot of effort. If you write a good game it's easier money, I think. Like a cook, you become better at cooking games, until you learn how to cook right.

**Comment by user1095108** [comment]
There, I fixed the `split()` for you.

**Comment by user706** [comment]
> There, I fixed the `split()` for you.

Ok, I'm using it here: https://github.com/user1095108/ca/pull/3/files#diff-ccdfb1e8f562283a4861e4c4e388da1f7d8feaf2e44c7ee28a65fc06aac92dacR27

So the thing about `split`, is that it then invokes `g`, which has **2 pointers** from the source.
```cpp
    split(beg, end, [&dst](T const * f, T const *l) {
        dst = std::copy(f, l, dst);
    });
```

As you can see, the destination `dst` is captured in the lambda.

But if the destination `dst` is also a `ca::array`, then I would like to optimize it as well (as explained [here](https://github.com/user1095108/ca/pull/3#issuecomment-1468985659), where I wrote about "it's damn hard"...); and for that I need a method of invoking a `g` with **3 pointers**:
https://github.com/user1095108/ca/pull/3/files#diff-ccdfb1e8f562283a4861e4c4e388da1f7d8feaf2e44c7ee28a65fc06aac92dacR38
```cpp
return ca::iterViaRaw(beg, end, dst, [](auto b, auto e, auto dst) { std::copy(b, e, dst); });
```

This is now superfast, as you can see by running it... once with [this comment](https://github.com/user1095108/ca/pull/3/files#diff-6009d730ca493e1ad401e869197b3429b4da00b1883059aaa402c0c12e78a2d5R3) in place (fast), and once uncommented (slow):
array.cpp
```cpp
//#define NO_CA_ARRAY_CONTRIB // uncommenting this line, will slow the copying into la2
```
It's a direct speedup of this code (from a constructor):
https://github.com/user1095108/ca/blob/82c95294ea22620ab8feb024cb676d3c6d8839e7/array.hpp#L109

I've explained what's going on in comments here
https://github.com/user1095108/ca/pull/3/files#diff-b37cceb5282c01145f3dd62773f61917c86cb4dcfd20bba31c2d65f66941a871R639

One can probably make it more generally usable... with the 3 arguments... by taking away some of the consts here:
https://github.com/user1095108/ca/pull/3/files#diff-b37cceb5282c01145f3dd62773f61917c86cb4dcfd20bba31c2d65f66941a871R614
```cpp
template <typename T, typename CA, typename T2, typename CA2>
constexpr auto iterViaRaw(const arrayiterator<T const, CA> & src_beg, const arrayiterator<T const, CA> & src_end, const arrayiterator<T2 , CA2> & dst, auto && g)
```

It would kindof be nice, to use it (or something similar) to also speed up these parts:
https://github.com/user1095108/ca/blob/82c95294ea22620ab8feb024cb676d3c6d8839e7/array.hpp#L186

(One could do a length check, first and then get rid of the 4th argument... and throw it into ca::iterViaRaw... something like that...)

PS: check my code in the diff is much smaller and nicer now, than with what I started with.

**Comment by user706** [comment]
> There, I fixed the `split()` for you.

Ok, I'm using it here: https://github.com/user1095108/ca/pull/3/files#diff-ccdfb1e8f562283a4861e4c4e388da1f7d8feaf2e44c7ee28a65fc06aac92dacR27

So the thing about `split`, is that it then invokes `g`, which has **2 pointers** from the source.
```cpp
    split(beg, end, [&dst](T const * f, T const *l) {
        dst = std::copy(f, l, dst);
    });
```

As you can see, the destination `dst` is captured in the lambda.

But if the destination `dst` is also a `ca::array`, then I would like to optimize it as well (as explained [here](https://github.com/user1095108/ca/pull/3#issuecomment-1468985659), where I wrote about "it's damn hard"...); and for that I need a method of invoking a `g` with **3 pointers**:
https://github.com/user1095108/ca/pull/3/files#diff-ccdfb1e8f562283a4861e4c4e388da1f7d8feaf2e44c7ee28a65fc06aac92dacR38
```cpp
return ca::iterViaRaw(beg, end, dst, [](auto b, auto e, auto dst) { std::copy(b, e, dst); });
```

This is now superfast, as you can see by running it... once with [this comment](https://github.com/user1095108/ca/pull/3/files#diff-6009d730ca493e1ad401e869197b3429b4da00b1883059aaa402c0c12e78a2d5R3) in place (fast), and once uncommented (slow):
array.cpp
```cpp
//#define NO_CA_ARRAY_CONTRIB // uncommenting this line, will slow the copying into la2
```
It's a direct speedup of this code (from a constructor):
https://github.com/user1095108/ca/blob/82c95294ea22620ab8feb024cb676d3c6d8839e7/array.hpp#L109

I've explained what's going on in comments here
https://github.com/user1095108/ca/pull/3/files#diff-b37cceb5282c01145f3dd62773f61917c86cb4dcfd20bba31c2d65f66941a871R639

One can probably make it more generally usable... with the 3 arguments... by taking away some of the consts here:
https://github.com/user1095108/ca/pull/3/files#diff-b37cceb5282c01145f3dd62773f61917c86cb4dcfd20bba31c2d65f66941a871R614
```cpp
template <typename T, typename CA, typename T2, typename CA2>
constexpr auto iterViaRaw(const arrayiterator<T const, CA> & src_beg, const arrayiterator<T const, CA> & src_end, const arrayiterator<T2 , CA2> & dst, auto && g)
```

It would kindof be nice, to use it (or something similar) to also speed up these parts:
https://github.com/user1095108/ca/blob/82c95294ea22620ab8feb024cb676d3c6d8839e7/array.hpp#L186

(One could do a length check, first and then get rid of the 4th argument... and throw it into ca::iterViaRaw... something like that...)

PS: check my code in the diff is much smaller and nicer now, than with what I started with.

**Comment by user1095108** [comment]
I provided a `copy.cpp` implementation.

**Comment by user706** [comment]
Hmmm... 

Yes but,....hmmm. Maybe this kind of stuff must be inside the library, otherwise the user will end up making mistakes.

Even you still have a mistake by the way... as far as I can see... (but I still think you're a great coder!)
https://github.com/user1095108/ca/blob/e0b542ca6cdb7871ddab29aaef13f64b2db51d59/copy.cpp#L20

Seems you were thinking about it, yourself, as can be seen in your commit here:
https://github.com/user1095108/ca/commit/9a0f6cdef9acaa2ea8bf94df66f1aa6472ef66bc

I think this is correct:
```cpp
auto const sz1(&d.data()[d.array_size()] - l);
/*
           3     9
        xxx------
           |     |
           l     array_size
*/
```

(Yes, I think it is not possible to have an array with size equal to `PTRDIFF_MAX`, 
so no need for `auto const sz1(&d.data()[d.array_size()-1] - l + 1);`.
Would it not be nice to have this change??? ->   `requires ((CAP > 0) && (CAP < PTRDIFF_MAX))` )

**Comment by user1095108** [comment]
`      auto const sz1(&d.data()[d.array_size() - 1] - l);
`
This is correct. If you make a thought experiment, you always need an extra node which acts as a kind of end-of-container marker. This space is wasted, but wasting it simplifies our code and results in higher performance. So, in this case, my query is, can I waste one node and occupy the rest?

As for this being in the library. No, it's an exercise for the coder.

EDIT: lol, in this case you're probably right though, you can overwrite everything even the final place.

As for the rest, take a look here: https://en.cppreference.com/w/c/types/ptrdiff_t

**Comment by user706** [comment]
Hu?

No. You can just copy to the end.
Thought experiment: The d circ-array has say... a million more nodes than
s, but it's current size is 3, and copying 1024 elements will cause wrap
around.

user1095108 ***@***.***> schrieb am Do., 16. März 2023, 21:58:

**Comment by user706** [comment]
> EDIT: lol, in this case you're probably right though, you can overwrite everything even the final place.

Yip

**Comment by user1095108** [comment]
I updated the repository accordingly.

**Comment by user706** [comment]
And still you don't sacrifice the millionth'ish last element, and just require `CAP < PTRDIFF_MAX`!!

**Comment by user706** [comment]
What exactly is the point of `copy.cpp`?

I mean... this is not the sort of code users should write.
(Should this not - one day - be part of the lib mechanism?)

(How do you like my std::copy overrides by the way?
I assume you probably don't like them... haha)

**Comment by user1095108** [comment]
ah no, I like the users, but I mostly wrote this for my own use. It's not like this is going to be a part of the Standard.

You know, I like to keep the library itself unencumbered. Yours is just a very specific application.

**Comment by user1095108** [comment]
anyway, I fixed `copy.cpp` yet again, but something like this should not be part of a library.

**Comment by user1095108** [comment]
Probably, now everything works as intended. The amount of disinformation concerning the ring buffer is frightening and its Wikipedia page sadly one of the best examples of that. Your ideas were very good.

**Pull request closed without merging**
